symbol_list = ['1INCHUSDT', 'AAVEUSDT', 'ADAUSDT', 'ALGOUSDT', 'ALICEUSDT', 'ATOMUSDT', 'AVAXUSDT', 'BALUSDT', 'BANDUSDT', 'BATUSDT', \
              'BCHUSDT', 'BELUSDT', 'BLZUSDT', 'BNBUSDT', 'CHZUSDT', 'COMPUSDT', 'COTIUSDT', 'CVCUSDT', \
              'DASHUSDT', 'DEFIUSDT', 'DODOUSDT', 'DOGEUSDT', 'DOTUSDT', 'EGLDUSDT', 'ENJUSDT', 'EOSUSDT', 'ETHUSDT', 'IOSTUSDT', 'IOTAUSDT', 'KNCUSDT', 'KSMUSDT', 'LINAUSDT', 'LINKUSDT', 'LITUSDT', 'LRCUSDT', 'LTCUSDT', 'LUNAUSDT', 'MANAUSDT', 'MATICUSDT', \
              'MKRUSDT', 'NEOUSDT', 'OMGUSDT', 'ONEUSDT', 'QTUMUSDT', 'REEFUSDT', 'RENUSDT', 'RSRUSDT', 'RUNEUSDT', 'RVNUSDT', 'SANDUSDT', \
              'SFPUSDT', 'SNXUSDT', 'SOLUSDT', 'SRMUSDT', 'STORJUSDT', 'SUSHIUSDT', 'THETAUSDT', 'TOMOUSDT', 'UNIUSDT', \
              'VETUSDT', 'WAVESUSDT', 'XEMUSDT', 'XLMUSDT', 'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'YFIIUSDT', 'ZECUSDT', 'ZRXUSDT']